import { useState, useEffect, useCallback, useRef } from "react";
import { supabase } from "./supabase";
import vehicleData from "./vehicle-data.json";

// ─── Vehicle Database Lookups ───
const ALL_MAKES = Object.keys(vehicleData).sort();

function getModels(make) {
  if (!make || !vehicleData[make]) return [];
  return Object.keys(vehicleData[make]).sort();
}

function getYears(make, model) {
  if (!make || !model || !vehicleData[make]?.[model]) return [];
  return Object.keys(vehicleData[make][model]).sort((a, b) => b - a);
}

function getTrims(make, model, year) {
  if (!make || !model || !year || !vehicleData[make]?.[model]?.[year]) return [];
  return vehicleData[make][model][year].map((t) => t.trim).sort();
}

const emptySpecData = () => ({
  front: {
    camber: { preferred: "", min: "", max: "" },
    caster: { preferred: "", min: "", max: "" },
    totalToe: { preferred: "", min: "", max: "" },
    individualToe: { preferred: "", min: "", max: "" },
  },
  rear: {
    camber: { preferred: "", min: "", max: "" },
    totalToe: { preferred: "", min: "", max: "" },
    individualToe: { preferred: "", min: "", max: "" },
  },
  thrustAngle: { preferred: "", min: "", max: "" },
  steerAheadAngle: { preferred: "", min: "", max: "" },
  maxSteeringAngle: { left: "", right: "" },
  setbackAngle: { preferred: "", min: "", max: "" },
});

const emptySpec = (techName = "") => ({
  id: null, // null = new, will be auto-generated by Supabase
  year: "",
  make: "",
  model: "",
  trim: "",
  notes: "",
  spec_data: emptySpecData(),
  created_by: techName,
  created_at: null,
  updated_at: null,
});

// ─── Icons ───
const IconPlus = () => <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg>;
const IconSearch = () => <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg>;
const IconCar = () => <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M5 17h14M5 17a2 2 0 01-2-2V9a2 2 0 012-2h1l2-3h8l2 3h1a2 2 0 012 2v6a2 2 0 01-2 2M5 17v1a1 1 0 001 1h1a1 1 0 001-1v-1m8 0v1a1 1 0 001 1h1a1 1 0 001-1v-1"/><circle cx="7.5" cy="14.5" r="1.5"/><circle cx="16.5" cy="14.5" r="1.5"/></svg>;
const IconSave = () => <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="M19 21H5a2 2 0 01-2-2V5a2 2 0 012-2h11l5 5v11a2 2 0 01-2 2z"/><polyline points="17 21 17 13 7 13 7 21"/><polyline points="7 3 7 8 15 8"/></svg>;
const IconTrash = () => <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="3 6 5 6 21 6"/><path d="M19 6l-1 14a2 2 0 01-2 2H8a2 2 0 01-2-2L5 6"/><path d="M10 11v6"/><path d="M14 11v6"/><path d="M9 6V4a1 1 0 011-1h4a1 1 0 011 1v2"/></svg>;
const IconCopy = () => <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1"/></svg>;
const IconExport = () => <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>;
const IconChevron = ({ open }) => <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" style={{ transform: open ? "rotate(90deg)" : "rotate(0deg)", transition: "transform 0.2s" }}><polyline points="9 18 15 12 9 6"/></svg>;
const IconEdit = () => <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M11 4H4a2 2 0 00-2 2v14a2 2 0 002 2h14a2 2 0 002-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 013 3L12 15l-4 1 1-4 9.5-9.5z"/></svg>;
const IconBack = () => <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><line x1="19" y1="12" x2="5" y2="12"/><polyline points="12 19 5 12 12 5"/></svg>;
const IconCheck = () => <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"/></svg>;
const IconDB = () => <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><ellipse cx="12" cy="5" rx="9" ry="3"/><path d="M21 12c0 1.66-4.03 3-9 3s-9-1.34-9-3"/><path d="M3 5v14c0 1.66 4.03 3 9 3s9-1.34 9-3V5"/></svg>;
const IconRefresh = () => <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="23 4 23 10 17 10"/><path d="M20.49 15a9 9 0 11-2.12-9.36L23 10"/></svg>;
const IconUser = () => <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"/><circle cx="12" cy="7" r="4"/></svg>;
const IconOnline = () => <svg width="8" height="8" viewBox="0 0 8 8"><circle cx="4" cy="4" r="4" fill="var(--c-green)"/></svg>;
const IconOffline = () => <svg width="8" height="8" viewBox="0 0 8 8"><circle cx="4" cy="4" r="4" fill="var(--c-red)"/></svg>;

// ─── Supabase Data Layer ───
async function fetchAllSpecs() {
  const { data, error } = await supabase
    .from("alignment_specs")
    .select("*")
    .order("make", { ascending: true })
    .order("model", { ascending: true })
    .order("year", { ascending: false });
  if (error) throw error;
  return data || [];
}

async function upsertSpec(spec) {
  const row = {
    year: spec.year,
    make: spec.make,
    model: spec.model,
    trim: spec.trim || "",
    notes: spec.notes || "",
    spec_data: spec.spec_data,
    created_by: spec.created_by || "",
    updated_at: new Date().toISOString(),
  };
  if (spec.id) {
    row.id = spec.id;
  }
  const { data, error } = await supabase
    .from("alignment_specs")
    .upsert(row, { onConflict: "id" })
    .select()
    .single();
  if (error) throw error;
  return data;
}

async function deleteSpec(id) {
  const { error } = await supabase
    .from("alignment_specs")
    .delete()
    .eq("id", id);
  if (error) throw error;
}

// ─── Shared Styles ───
const inputStyle = {
  width: "100%", padding: "10px", border: "1.5px solid var(--c-border)",
  borderRadius: "7px", fontSize: "14px", fontFamily: "inherit",
  background: "var(--c-input-bg)", color: "var(--c-text)", outline: "none",
  transition: "border-color 0.2s, box-shadow 0.2s", boxSizing: "border-box",
};

const inputLabel = {
  position: "absolute", top: "-7px", right: "8px", fontSize: "9px",
  fontWeight: 700, letterSpacing: "0.08em", color: "var(--c-text-dim)",
  background: "var(--c-surface)", padding: "0 4px",
};

const btnPrimary = {
  display: "inline-flex", alignItems: "center", gap: "6px",
  padding: "10px 20px", border: "none", borderRadius: "8px",
  background: "var(--c-amber)", color: "#1a1a1a",
  fontSize: "13px", fontWeight: 700, cursor: "pointer",
  letterSpacing: "0.03em", fontFamily: "inherit", transition: "all 0.15s",
};

const btnSecondary = {
  ...btnPrimary, background: "var(--c-surface-raised)",
  color: "var(--c-text)", border: "1px solid var(--c-border)",
};

const btnDanger = {
  ...btnSecondary, color: "var(--c-red)", borderColor: "var(--c-red-dim)",
};

const labelStyle = {
  display: "block", fontSize: "11px", fontWeight: 700, color: "var(--c-text-dim)",
  letterSpacing: "0.06em", textTransform: "uppercase", marginBottom: "5px",
};

// ─── Angle Input Row ───
function AngleRow({ label, data, onChange }) {
  return (
    <div style={{ display: "grid", gridTemplateColumns: "140px 1fr 1fr 1fr", gap: "8px", alignItems: "center" }}>
      <span style={{ fontSize: "13px", color: "var(--c-text-dim)", fontWeight: 600, letterSpacing: "0.02em" }}>{label}</span>
      {["preferred", "min", "max"].map((field) => (
        <div key={field} style={{ position: "relative" }}>
          <input
            type="number" step="0.01"
            value={data[field]}
            onChange={(e) => onChange({ ...data, [field]: e.target.value })}
            placeholder={field === "preferred" ? "Pref" : field === "min" ? "Min" : "Max"}
            style={inputStyle}
          />
          <span style={inputLabel}>{field === "preferred" ? "PREF" : field.toUpperCase()}</span>
        </div>
      ))}
    </div>
  );
}

// ─── Collapsible Section ───
function Section({ title, children, defaultOpen = true, accent = "var(--c-amber)" }) {
  const [open, setOpen] = useState(defaultOpen);
  return (
    <div style={{
      border: "1px solid var(--c-border)", borderRadius: "10px",
      overflow: "hidden", background: "var(--c-surface)", marginBottom: "12px",
    }}>
      <button onClick={() => setOpen(!open)} style={{
        width: "100%", display: "flex", alignItems: "center", gap: "10px",
        padding: "14px 16px", border: "none", background: "transparent",
        cursor: "pointer", fontSize: "14px", fontWeight: 700,
        color: "var(--c-text)", letterSpacing: "0.04em", textTransform: "uppercase",
        fontFamily: "inherit",
      }}>
        <span style={{ width: "4px", height: "20px", borderRadius: "2px", background: accent, flexShrink: 0 }} />
        <IconChevron open={open} />
        {title}
      </button>
      {open && (
        <div className="animate-in" style={{ padding: "4px 16px 16px", display: "flex", flexDirection: "column", gap: "10px" }}>
          {children}
        </div>
      )}
    </div>
  );
}

// ─── Toast ───
function Toast({ message, visible, type = "success" }) {
  return (
    <div style={{
      position: "fixed", bottom: 24, left: "50%",
      transform: `translateX(-50%) translateY(${visible ? 0 : 20}px)`,
      background: type === "error" ? "var(--c-red)" : "#1a1a1a",
      color: "#fff", padding: "10px 22px", borderRadius: "8px",
      fontSize: "13px", fontWeight: 600, display: "flex", alignItems: "center", gap: "8px",
      opacity: visible ? 1 : 0, transition: "all 0.3s ease", zIndex: 999,
      boxShadow: "0 8px 32px rgba(0,0,0,0.3)",
    }}>
      {type === "success" && <IconCheck />} {message}
    </div>
  );
}

// ─── Name Prompt (shown on first visit) ───
function NamePrompt({ onSubmit }) {
  const [name, setName] = useState("");
  return (
    <div style={{
      minHeight: "100vh", display: "flex", alignItems: "center", justifyContent: "center",
      background: "var(--c-bg)", padding: "20px",
    }}>
      <div className="animate-in" style={{
        background: "var(--c-surface)", border: "1px solid var(--c-border)",
        borderRadius: "16px", padding: "40px", maxWidth: "420px", width: "100%",
        textAlign: "center",
      }}>
        <div style={{ color: "var(--c-amber)", marginBottom: 16 }}><IconDB /></div>
        <h1 style={{ fontSize: "22px", fontWeight: 800, marginBottom: 6 }}>
          AlignSpec<span style={{ color: "var(--c-amber)" }}>DB</span>
        </h1>
        <p style={{ fontSize: "13px", color: "var(--c-text-dim)", marginBottom: 28, lineHeight: 1.5 }}>
          OEM Alignment Specification Database<br />
          Enter your name so the team knows who added each spec.
        </p>
        <div style={{ textAlign: "left", marginBottom: 16 }}>
          <label style={labelStyle}>Your Name</label>
          <input
            type="text" value={name}
            onChange={(e) => setName(e.target.value)}
            onKeyDown={(e) => { if (e.key === "Enter" && name.trim()) onSubmit(name.trim()); }}
            placeholder="e.g. Mike, Sarah, Tech Bay 3"
            style={inputStyle}
            autoFocus
          />
        </div>
        <button
          onClick={() => { if (name.trim()) onSubmit(name.trim()); }}
          disabled={!name.trim()}
          style={{ ...btnPrimary, width: "100%", justifyContent: "center", padding: "12px", fontSize: "14px", opacity: name.trim() ? 1 : 0.5 }}
        >
          <IconUser /> Continue
        </button>
      </div>
    </div>
  );
}

// ─── Main App ───
export default function App() {
  const [techName, setTechName] = useState(() => localStorage.getItem("alignspec_tech_name") || "");
  const [specs, setSpecs] = useState([]);
  const [view, setView] = useState("list");
  const [editingSpec, setEditingSpec] = useState(null);
  const [search, setSearch] = useState("");
  const [filterMake, setFilterMake] = useState("");
  const [filterYear, setFilterYear] = useState("");
  const [toast, setToast] = useState({ message: "", visible: false, type: "success" });
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [connected, setConnected] = useState(true);
  const fileInputRef = useRef(null);

  const showToast = useCallback((msg, type = "success") => {
    setToast({ message: msg, visible: true, type });
    setTimeout(() => setToast((t) => ({ ...t, visible: false })), 2800);
  }, []);

  // Save tech name
  const handleSetName = (name) => {
    setTechName(name);
    localStorage.setItem("alignspec_tech_name", name);
  };

  // Load specs from Supabase
  const loadSpecs = useCallback(async () => {
    try {
      const data = await fetchAllSpecs();
      setSpecs(data);
      setConnected(true);
    } catch (err) {
      console.error("Failed to load:", err);
      setConnected(false);
      showToast("Failed to connect to database", "error");
    } finally {
      setLoading(false);
    }
  }, [showToast]);

  useEffect(() => {
    if (techName) loadSpecs();
  }, [techName, loadSpecs]);

  // Real-time subscription
  useEffect(() => {
    if (!techName) return;
    const channel = supabase
      .channel("alignment_specs_changes")
      .on("postgres_changes", { event: "*", schema: "public", table: "alignment_specs" }, () => {
        loadSpecs(); // reload on any change
      })
      .subscribe();
    return () => { supabase.removeChannel(channel); };
  }, [techName, loadSpecs]);

  const handleNewSpec = () => {
    setEditingSpec(emptySpec(techName));
    setView("form");
  };

  const handleEditSpec = (spec) => {
    const clone = JSON.parse(JSON.stringify(spec));
    // Ensure spec_data has all fields (for older records that might be missing some)
    clone.spec_data = { ...emptySpecData(), ...clone.spec_data };
    if (clone.spec_data.front) clone.spec_data.front = { ...emptySpecData().front, ...clone.spec_data.front };
    if (clone.spec_data.rear) clone.spec_data.rear = { ...emptySpecData().rear, ...clone.spec_data.rear };
    setEditingSpec(clone);
    setView("form");
  };

  const handleDuplicateSpec = (spec) => {
    const dup = JSON.parse(JSON.stringify(spec));
    dup.id = null; // Will create new
    dup.year = "";
    dup.model = dup.model + " (copy)";
    dup.created_by = techName;
    dup.created_at = null;
    dup.updated_at = null;
    dup.spec_data = { ...emptySpecData(), ...dup.spec_data };
    if (dup.spec_data.front) dup.spec_data.front = { ...emptySpecData().front, ...dup.spec_data.front };
    if (dup.spec_data.rear) dup.spec_data.rear = { ...emptySpecData().rear, ...dup.spec_data.rear };
    setEditingSpec(dup);
    setView("form");
    showToast("Duplicated — edit the copy below");
  };

  const handleSaveSpec = async (spec) => {
    setSaving(true);
    try {
      await upsertSpec(spec);
      await loadSpecs();
      setView("list");
      setEditingSpec(null);
      showToast(spec.id ? "Spec updated" : "New spec saved");
    } catch (err) {
      console.error("Save failed:", err);
      showToast("Save failed — check connection", "error");
    } finally {
      setSaving(false);
    }
  };

  const handleDeleteSpec = async (id) => {
    try {
      await deleteSpec(id);
      await loadSpecs();
      showToast("Spec deleted");
      if (view === "form") { setView("list"); setEditingSpec(null); }
    } catch (err) {
      showToast("Delete failed", "error");
    }
  };

  const handleExport = () => {
    const blob = new Blob([JSON.stringify(specs, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `alignment-specs-${new Date().toISOString().split("T")[0]}.json`;
    a.click();
    URL.revokeObjectURL(url);
    showToast(`Exported ${specs.length} specs`);
  };

  const handleImport = (e) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = async (ev) => {
      try {
        const data = JSON.parse(ev.target.result);
        if (!Array.isArray(data)) throw new Error("Invalid");
        let count = 0;
        for (const item of data) {
          if (!item.year || !item.make || !item.model) continue;
          await upsertSpec({
            ...item,
            id: null, // create new entries
            created_by: item.created_by || techName,
            spec_data: item.spec_data || emptySpecData(),
          });
          count++;
        }
        await loadSpecs();
        showToast(`Imported ${count} specs`);
      } catch {
        showToast("Import failed — check file format", "error");
      }
    };
    reader.readAsText(file);
    e.target.value = "";
  };

  // Filters
  const filtered = specs.filter((s) => {
    const q = search.toLowerCase();
    const matchesSearch = !q || `${s.year} ${s.make} ${s.model} ${s.trim}`.toLowerCase().includes(q);
    const matchesMake = !filterMake || s.make === filterMake;
    const matchesYear = !filterYear || s.year === filterYear;
    return matchesSearch && matchesMake && matchesYear;
  });

  const uniqueMakes = [...new Set(specs.map((s) => s.make))].filter(Boolean).sort();
  const stats = {
    total: specs.length,
    makes: new Set(specs.map((s) => s.make)).size,
    models: new Set(specs.map((s) => `${s.make}-${s.model}`)).size,
  };

  if (!techName) return <NamePrompt onSubmit={handleSetName} />;

  if (loading) {
    return (
      <div style={{ minHeight: "100vh", display: "flex", alignItems: "center", justifyContent: "center", background: "var(--c-bg)" }}>
        <div style={{ textAlign: "center", color: "var(--c-text-dim)" }}>
          <div className="pulse" style={{ color: "var(--c-amber)" }}><IconDB /></div>
          <p style={{ marginTop: 12, fontSize: "14px", fontWeight: 600 }}>Connecting to database...</p>
        </div>
      </div>
    );
  }

  return (
    <div style={{ minHeight: "100vh", display: "flex", flexDirection: "column", background: "var(--c-bg)" }}>
      {/* Header */}
      <div style={{
        display: "flex", alignItems: "center", justifyContent: "space-between",
        padding: "16px 20px", borderBottom: "1px solid var(--c-border)",
        background: "var(--c-surface)", flexWrap: "wrap", gap: "10px",
      }}>
        <div style={{ display: "flex", alignItems: "center", gap: "12px" }}>
          {view === "form" && (
            <button onClick={() => { setView("list"); setEditingSpec(null); }} style={{ ...btnSecondary, padding: "8px 12px" }}>
              <IconBack />
            </button>
          )}
          <div>
            <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
              <span style={{ color: "var(--c-amber)" }}><IconDB /></span>
              <h1 style={{ fontSize: "17px", fontWeight: 800, letterSpacing: "-0.01em" }}>
                AlignSpec<span style={{ color: "var(--c-amber)" }}>DB</span>
              </h1>
              <span style={{ display: "flex", alignItems: "center", gap: "4px", fontSize: "10px", color: "var(--c-text-dim)", fontWeight: 600 }}>
                {connected ? <IconOnline /> : <IconOffline />}
                {connected ? "LIVE" : "OFFLINE"}
              </span>
            </div>
            <p style={{ fontSize: "11px", color: "var(--c-text-dim)", marginTop: 1, letterSpacing: "0.04em", textTransform: "uppercase", fontWeight: 600 }}>
              {view === "form" ? (editingSpec?.id ? "Edit Specification" : "New Specification") : "Shared OEM Alignment Database"}
            </p>
          </div>
        </div>
        <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
          <span style={{
            display: "flex", alignItems: "center", gap: "5px", fontSize: "12px",
            color: "var(--c-text-dim)", background: "var(--c-surface-raised)",
            padding: "5px 10px", borderRadius: "6px", fontWeight: 600,
          }}>
            <IconUser /> {techName}
          </span>
          {view === "list" && (
            <button onClick={handleNewSpec} style={btnPrimary}>
              <IconPlus /> Add Spec
            </button>
          )}
        </div>
      </div>

      {view === "list" ? (
        <div style={{ padding: "16px 20px 24px", overflow: "auto", flex: 1 }}>
          {/* Stats */}
          <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: "10px", marginBottom: "14px" }}>
            {[
              { label: "Total Specs", value: stats.total, color: "var(--c-amber)" },
              { label: "Makes", value: stats.makes, color: "var(--c-green)" },
              { label: "Models", value: stats.models, color: "var(--c-purple)" },
            ].map((s) => (
              <div key={s.label} style={{
                background: "var(--c-surface)", border: "1px solid var(--c-border)",
                borderRadius: "10px", padding: "12px 14px",
              }}>
                <div style={{ fontSize: "20px", fontWeight: 800, color: s.color, fontFamily: "'JetBrains Mono', monospace" }}>{s.value}</div>
                <div style={{ fontSize: "10px", color: "var(--c-text-dim)", fontWeight: 600, letterSpacing: "0.06em", textTransform: "uppercase", marginTop: 2 }}>{s.label}</div>
              </div>
            ))}
          </div>

          {/* Search + Filters */}
          <div style={{ display: "flex", gap: "8px", marginBottom: "12px", flexWrap: "wrap" }}>
            <div style={{ flex: 1, minWidth: "180px", position: "relative" }}>
              <span style={{ position: "absolute", left: 12, top: "50%", transform: "translateY(-50%)", color: "var(--c-text-dim)" }}><IconSearch /></span>
              <input type="text" value={search} onChange={(e) => setSearch(e.target.value)}
                placeholder="Search year, make, model..." style={{ ...inputStyle, paddingLeft: 38, background: "var(--c-surface)" }} />
            </div>
            <select value={filterMake} onChange={(e) => setFilterMake(e.target.value)} style={{ ...inputStyle, width: "150px", background: "var(--c-surface)", cursor: "pointer" }}>
              <option value="">All Makes</option>
              {uniqueMakes.map((m) => <option key={m} value={m}>{m}</option>)}
            </select>
            <select value={filterYear} onChange={(e) => setFilterYear(e.target.value)} style={{ ...inputStyle, width: "110px", background: "var(--c-surface)", cursor: "pointer" }}>
              <option value="">All Years</option>
              {[...new Set(specs.map(s => s.year))].filter(Boolean).sort((a, b) => b - a).map((y) => <option key={y} value={y}>{y}</option>)}
            </select>
          </div>

          {/* Actions */}
          <div style={{ display: "flex", gap: "8px", marginBottom: "14px", flexWrap: "wrap" }}>
            <button onClick={loadSpecs} style={{ ...btnSecondary, padding: "8px 12px", fontSize: "12px" }}>
              <IconRefresh /> Refresh
            </button>
            <button onClick={handleExport} disabled={specs.length === 0} style={{ ...btnSecondary, padding: "8px 12px", fontSize: "12px" }}>
              <IconExport /> Export JSON
            </button>
            <button onClick={() => fileInputRef.current?.click()} style={{ ...btnSecondary, padding: "8px 12px", fontSize: "12px" }}>
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4"/><polyline points="17 8 12 3 7 8"/><line x1="12" y1="3" x2="12" y2="15"/></svg> Import JSON
            </button>
            <button onClick={() => { localStorage.removeItem("alignspec_tech_name"); setTechName(""); }}
              style={{ ...btnSecondary, padding: "8px 12px", fontSize: "12px", marginLeft: "auto" }}>
              Switch User
            </button>
          </div>

          {/* Spec List */}
          {filtered.length === 0 ? (
            <div style={{
              textAlign: "center", padding: "50px 20px", background: "var(--c-surface)",
              borderRadius: "12px", border: "1px dashed var(--c-border)",
            }}>
              <div style={{ color: "var(--c-text-dim)", marginBottom: 8 }}><IconCar /></div>
              <p style={{ color: "var(--c-text-dim)", fontSize: "14px", fontWeight: 600, marginBottom: 4 }}>
                {specs.length === 0 ? "No specs in database yet" : "No results found"}
              </p>
              <p style={{ color: "var(--c-text-dim)", fontSize: "12px", opacity: 0.7, marginBottom: 16 }}>
                {specs.length === 0 ? "Add your first vehicle alignment spec to get started." : "Try adjusting your search or filters."}
              </p>
              {specs.length === 0 && <button onClick={handleNewSpec} style={btnPrimary}><IconPlus /> Add First Spec</button>}
            </div>
          ) : (
            <div style={{ display: "flex", flexDirection: "column", gap: "6px" }}>
              {filtered.map((spec) => {
                const hasData = (obj) => obj && Object.values(obj).some((v) => typeof v === "object" ? hasData(v) : v !== "");
                const sd = spec.spec_data || {};
                const frontFilled = hasData(sd.front);
                const rearFilled = hasData(sd.rear);
                return (
                  <div key={spec.id} onClick={() => handleEditSpec(spec)}
                    onMouseEnter={(e) => e.currentTarget.style.borderColor = "var(--c-amber)"}
                    onMouseLeave={(e) => e.currentTarget.style.borderColor = "var(--c-border)"}
                    style={{
                      background: "var(--c-surface)", border: "1px solid var(--c-border)",
                      borderRadius: "10px", padding: "12px 14px", display: "flex",
                      alignItems: "center", justifyContent: "space-between",
                      cursor: "pointer", transition: "border-color 0.2s",
                    }}>
                    <div style={{ display: "flex", alignItems: "center", gap: "12px", flex: 1, minWidth: 0 }}>
                      <div style={{
                        width: 40, height: 40, borderRadius: "9px", background: "var(--c-amber-dim)",
                        display: "flex", alignItems: "center", justifyContent: "center",
                        color: "var(--c-amber)", flexShrink: 0,
                      }}><IconCar /></div>
                      <div style={{ minWidth: 0 }}>
                        <div style={{ fontSize: "14px", fontWeight: 700, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>
                          {spec.year || "?"} {spec.make || "Unknown"} {spec.model || ""}
                        </div>
                        <div style={{ fontSize: "11px", color: "var(--c-text-dim)", display: "flex", gap: "10px", marginTop: 2, flexWrap: "wrap" }}>
                          {spec.trim && <span>{spec.trim}</span>}
                          <span style={{ display: "flex", alignItems: "center", gap: "3px" }}>
                            <span style={{ width: 6, height: 6, borderRadius: "50%", background: frontFilled ? "var(--c-green)" : "var(--c-border)" }} /> Front
                          </span>
                          <span style={{ display: "flex", alignItems: "center", gap: "3px" }}>
                            <span style={{ width: 6, height: 6, borderRadius: "50%", background: rearFilled ? "var(--c-green)" : "var(--c-border)" }} /> Rear
                          </span>
                          {spec.created_by && <span style={{ opacity: 0.7 }}>by {spec.created_by}</span>}
                        </div>
                      </div>
                    </div>
                    <div style={{ display: "flex", gap: "2px", flexShrink: 0 }} onClick={(e) => e.stopPropagation()}>
                      <button onClick={() => handleDuplicateSpec(spec)} title="Duplicate" style={{ ...btnSecondary, padding: "7px", border: "none", background: "transparent" }}><IconCopy /></button>
                      <button onClick={() => handleEditSpec(spec)} title="Edit" style={{ ...btnSecondary, padding: "7px", border: "none", background: "transparent" }}><IconEdit /></button>
                      <button onClick={() => { if (confirm(`Delete ${spec.year} ${spec.make} ${spec.model}?`)) handleDeleteSpec(spec.id); }}
                        title="Delete" style={{ ...btnDanger, padding: "7px", border: "none", background: "transparent" }}><IconTrash /></button>
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      ) : (
        <FormView
          spec={editingSpec} setSpec={setEditingSpec}
          onSave={handleSaveSpec} saving={saving}
          onDelete={() => handleDeleteSpec(editingSpec.id)}
          isNew={!editingSpec?.id}
        />
      )}

      <input ref={fileInputRef} type="file" accept=".json" onChange={handleImport} style={{ display: "none" }} />
      <Toast message={toast.message} visible={toast.visible} type={toast.type} />
    </div>
  );
}

// ─── Form View ───
function FormView({ spec, setSpec, onSave, saving, onDelete, isNew }) {
  if (!spec) return null;
  const sd = spec.spec_data || emptySpecData();
  const [manualEntry, setManualEntry] = useState(false);

  // Check if current values are in the database (for editing existing specs)
  const isInDB = spec.make && ALL_MAKES.includes(spec.make);

  // Cascading dropdown options
  const models = getModels(spec.make);
  const years = getYears(spec.make, spec.model);
  const trims = getTrims(spec.make, spec.model, spec.year);

  const handleMakeChange = (value) => {
    if (value === "__manual") {
      setManualEntry(true);
      setSpec({ ...spec, make: "", model: "", year: "", trim: "" });
      return;
    }
    setManualEntry(false);
    setSpec({ ...spec, make: value, model: "", year: "", trim: "" });
  };

  const handleModelChange = (value) => {
    if (value === "__manual") {
      setManualEntry(true);
      return;
    }
    setSpec({ ...spec, model: value, year: "", trim: "" });
  };

  const handleYearChange = (value) => {
    setSpec({ ...spec, year: value, trim: "" });
  };

  const handleTrimChange = (value) => {
    setSpec({ ...spec, trim: value });
  };

  const updateField = (field, value) => setSpec({ ...spec, [field]: value });
  const updateSpecData = (path, value) => {
    const newSD = JSON.parse(JSON.stringify(sd));
    const keys = path.split(".");
    let obj = newSD;
    for (let i = 0; i < keys.length - 1; i++) obj = obj[keys[i]];
    obj[keys[keys.length - 1]] = value;
    setSpec({ ...spec, spec_data: newSD });
  };

  const selectStyle = { ...inputStyle, cursor: "pointer" };
  const disabledSelectStyle = { ...inputStyle, cursor: "not-allowed", opacity: 0.6 };

  return (
    <div className="animate-in" style={{ padding: "16px 20px 50px", overflow: "auto", flex: 1, maxWidth: "720px", margin: "0 auto", width: "100%" }}>
      <Section title="Vehicle Information" accent="var(--c-amber)">
        {/* Manual entry toggle */}
        <div style={{ display: "flex", alignItems: "center", justifyContent: "flex-end", marginBottom: 4 }}>
          <button
            onClick={() => {
              setManualEntry(!manualEntry);
              if (manualEntry) setSpec({ ...spec, make: "", model: "", year: "", trim: "" });
            }}
            style={{
              background: "none", border: "1px solid var(--c-border)", borderRadius: "6px",
              padding: "5px 10px", fontSize: "11px", fontWeight: 600, fontFamily: "inherit",
              color: manualEntry ? "var(--c-amber)" : "var(--c-text-dim)",
              cursor: "pointer", letterSpacing: "0.03em",
            }}
          >
            {manualEntry ? "← Back to dropdowns" : "Vehicle not listed? Type manually"}
          </button>
        </div>

        {manualEntry ? (
          /* ─── Manual entry mode ─── */
          <>
            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "10px" }}>
              <div>
                <label style={labelStyle}>Make *</label>
                <input type="text" value={spec.make} onChange={(e) => updateField("make", e.target.value)}
                  placeholder="e.g. Toyota" style={inputStyle} autoFocus />
              </div>
              <div>
                <label style={labelStyle}>Model *</label>
                <input type="text" value={spec.model} onChange={(e) => updateField("model", e.target.value)}
                  placeholder="e.g. Camry" style={inputStyle} />
              </div>
            </div>
            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "10px" }}>
              <div>
                <label style={labelStyle}>Year *</label>
                <input type="text" value={spec.year} onChange={(e) => updateField("year", e.target.value)}
                  placeholder="e.g. 2024" style={inputStyle} />
              </div>
              <div>
                <label style={labelStyle}>Trim / Engine</label>
                <input type="text" value={spec.trim} onChange={(e) => updateField("trim", e.target.value)}
                  placeholder="e.g. SE, 2.5L, AWD" style={inputStyle} />
              </div>
            </div>
          </>
        ) : (
          /* ─── Cascading dropdown mode ─── */
          <>
            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "10px" }}>
              <div>
                <label style={labelStyle}>Make *</label>
                <select value={ALL_MAKES.includes(spec.make) ? spec.make : ""}
                  onChange={(e) => handleMakeChange(e.target.value)} style={selectStyle}>
                  <option value="">Select Make</option>
                  {ALL_MAKES.map((m) => <option key={m} value={m}>{m}</option>)}
                  <option value="__manual">— Not listed —</option>
                </select>
              </div>
              <div>
                <label style={labelStyle}>Model *</label>
                <select value={models.includes(spec.model) ? spec.model : ""}
                  onChange={(e) => handleModelChange(e.target.value)}
                  disabled={!spec.make}
                  style={spec.make ? selectStyle : disabledSelectStyle}>
                  <option value="">{spec.make ? "Select Model" : "Select Make first"}</option>
                  {models.map((m) => <option key={m} value={m}>{m}</option>)}
                  {spec.make && <option value="__manual">— Not listed —</option>}
                </select>
              </div>
            </div>
            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "10px" }}>
              <div>
                <label style={labelStyle}>Year *</label>
                <select value={years.includes(spec.year) ? spec.year : ""}
                  onChange={(e) => handleYearChange(e.target.value)}
                  disabled={!spec.model}
                  style={spec.model ? selectStyle : disabledSelectStyle}>
                  <option value="">{spec.model ? "Select Year" : "Select Model first"}</option>
                  {years.map((y) => <option key={y} value={y}>{y}</option>)}
                </select>
              </div>
              <div>
                <label style={labelStyle}>Trim / Engine</label>
                <select value={trims.includes(spec.trim) ? spec.trim : ""}
                  onChange={(e) => handleTrimChange(e.target.value)}
                  disabled={!spec.year}
                  style={spec.year ? selectStyle : disabledSelectStyle}>
                  <option value="">{spec.year ? "Select Trim" : "Select Year first"}</option>
                  {trims.map((t) => <option key={t} value={t}>{t}</option>)}
                </select>
              </div>
            </div>
          </>
        )}

        <div>
          <label style={labelStyle}>Notes</label>
          <textarea value={spec.notes} onChange={(e) => updateField("notes", e.target.value)}
            placeholder="Special instructions, suspension type, etc." rows={2}
            style={{ ...inputStyle, resize: "vertical", fontFamily: "inherit" }} />
        </div>
      </Section>

      <Section title="Front Axle Specs (degrees)" accent="var(--c-green)">
        <div style={{ fontSize: "11px", color: "var(--c-text-dim)", marginBottom: 4, fontWeight: 600, letterSpacing: "0.03em" }}>
          All angles in degrees. +Camber = top out. +Caster = top rear. +Toe = toe-in.
        </div>
        <AngleRow label="Camber" data={sd.front.camber} onChange={(v) => updateSpecData("front.camber", v)} />
        <AngleRow label="Caster" data={sd.front.caster} onChange={(v) => updateSpecData("front.caster", v)} />
        <AngleRow label="Total Toe" data={sd.front.totalToe} onChange={(v) => updateSpecData("front.totalToe", v)} />
        <AngleRow label="Individual Toe" data={sd.front.individualToe} onChange={(v) => updateSpecData("front.individualToe", v)} />
      </Section>

      <Section title="Rear Axle Specs (degrees)" accent="var(--c-purple)">
        <AngleRow label="Camber" data={sd.rear.camber} onChange={(v) => updateSpecData("rear.camber", v)} />
        <AngleRow label="Total Toe" data={sd.rear.totalToe} onChange={(v) => updateSpecData("rear.totalToe", v)} />
        <AngleRow label="Individual Toe" data={sd.rear.individualToe} onChange={(v) => updateSpecData("rear.individualToe", v)} />
      </Section>

      <Section title="Additional Angles" accent="var(--c-text-dim)" defaultOpen={false}>
        <AngleRow label="Thrust Angle" data={sd.thrustAngle} onChange={(v) => updateSpecData("thrustAngle", v)} />
        <AngleRow label="Steer Ahead" data={sd.steerAheadAngle} onChange={(v) => updateSpecData("steerAheadAngle", v)} />
        <AngleRow label="Setback" data={sd.setbackAngle} onChange={(v) => updateSpecData("setbackAngle", v)} />
        <div style={{ display: "grid", gridTemplateColumns: "140px 1fr 1fr", gap: "8px", alignItems: "center" }}>
          <span style={{ fontSize: "13px", color: "var(--c-text-dim)", fontWeight: 600 }}>Max Steer Angle</span>
          <div style={{ position: "relative" }}>
            <input type="number" step="0.1" value={sd.maxSteeringAngle.left}
              onChange={(e) => updateSpecData("maxSteeringAngle.left", e.target.value)} placeholder="Left" style={inputStyle} />
            <span style={inputLabel}>LEFT</span>
          </div>
          <div style={{ position: "relative" }}>
            <input type="number" step="0.1" value={sd.maxSteeringAngle.right}
              onChange={(e) => updateSpecData("maxSteeringAngle.right", e.target.value)} placeholder="Right" style={inputStyle} />
            <span style={inputLabel}>RIGHT</span>
          </div>
        </div>
      </Section>

      <div style={{ display: "flex", gap: "10px", justifyContent: "space-between", marginTop: "8px" }}>
        <div>
          {!isNew && (
            <button onClick={() => { if (confirm("Delete permanently?")) onDelete(); }} style={btnDanger}>
              <IconTrash /> Delete
            </button>
          )}
        </div>
        <button disabled={saving}
          onClick={() => {
            if (!spec.year || !spec.make || !spec.model) { alert("Please fill in Year, Make, and Model."); return; }
            onSave(spec);
          }}
          style={{ ...btnPrimary, padding: "12px 28px", fontSize: "14px", opacity: saving ? 0.6 : 1 }}>
          <IconSave /> {saving ? "Saving..." : isNew ? "Save Spec" : "Update Spec"}
        </button>
      </div>
    </div>
  );
}
